### ISSUE TITLE
Language choose option

### ISSUE THREAD

**Issue by bestplay9384** [php-tmdb/symfony#15]
Hey guys,

Is there any option to change "on-the-fly" language of requested elements via tmdb api? 
It would be so good if we can integrate it with **Symfony** native _Translations/Locale_ module. 
Is it possible in current version?

Thanks for help! :)

**Comment by bestplay9384** [comment]
To describe precisely what i want to do for example:
I would like to have routes like /movie/ID/en or /movie/ID/pl where i want to get info about movie in english or polish language. I don't want to copy every data in database, it will be better to save it in cache, so one movie should have cached version fo english one and another for polish one. 

Can your plugin deal with it?

**Comment by wtfzdotnet** [comment]
Little too late I guess, but you know what they say... :laughing: 

Big update coming soon, I will take the varying of cache into account, thanks!
