### ISSUE TITLE
Deprecation notices with latest symfony versions

### ISSUE THREAD

**Issue by greg0ire** [php-tmdb/symfony#24]
> Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "tmdb.search_repository" service to "Tmdb\Repository\SearchRepository" instead.

The solution?

1. change the service ids to match the FQCNs
2. alias the services to the old services ids
3. ~~deprecate the aliases : https://symfony.com/doc/current/service_container/alias_private.html#deprecating-services (not sure if that works)~~ it does not work

**Comment by wtfzdotnet** [comment]
Changes will come soon in #29 to correct this, I will also keep an eye on those deprecations for the old aliases that are in place now. :-)
