### ISSUE TITLE
Symfony 5 compatibility

### ISSUE THREAD

**Issue by JimmyTournemaine** [php-tmdb/symfony#27]
Hello,

I'm using your bundle since Symfony 2 and it is working fine.

I have to migrate my application to Symfony 5.
Any plan to make your bundle compatible ?

**Comment by ivan1986** [comment]
https://github.com/php-tmdb/symfony/pull/28

**Comment by Wimble84** [comment]
I encounter the same problem with a fresh installation on Symfony 4.4.8

**Comment by wtfzdotnet** [comment]
There's a "dev" release floating around that @ivan1986 metioned, better fix coming soon in #29
