### ISSUE TITLE
phpunit-bridge conflict in Symfony 5

### ISSUE THREAD

**Issue by danielkoster** [php-tmdb/symfony#33]
Hi! I'm trying to use this library in a Symfony 5 project, but ran into a composer conflict. This seems to be because Symfony adds a "require: 5.2.*" to the "extra" configuration in composer.json.

Because this bundle requires `"symfony/phpunit-bridge": "^4.4"` this creates a conflict. I think this could be resolved by also accepting `<6`, as is done with the other Symfony dependencies.

`"symfony/phpunit-bridge": "^4.4",` would become `"symfony/phpunit-bridge": "^4.4 || <6",`.

Composer output:
```
$ composer require php-tmdb/symfony
Using version ^4.0 for php-tmdb/symfony
./composer.json has been updated
Running composer update php-tmdb/symfony
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - php-tmdb/symfony[4.0.4, ..., 4.0.x-dev] require symfony/phpunit-bridge ^4.4 -> found symfony/phpunit-bridge[v4.4.0-BETA1, ..., 4.4.x-dev] but it conflicts with your root composer.json require (^5.2).
    - php-tmdb/symfony[4.0.0, ..., 4.0.3] require symfony/phpunit-bridge ^4.2 -> found symfony/phpunit-bridge[v4.2.0-BETA1, ..., 4.4.x-dev] but it conflicts with your root composer.json require (^5.2).
    - Root composer.json requires php-tmdb/symfony ^4.0 -> satisfiable by php-tmdb/symfony[4.0.0, ..., 4.0.x-dev].
```

**Comment by wtfzdotnet** [comment]
Was able to reproduce after installing a symfony project, I'll get a fix out soon, just have to make sure CI will catch this in the future.

**Comment by wtfzdotnet** [comment]
Given the lack of time at my hands these past and coming weeks I'm simply going to take your suggested changes and commit these right now. I'll get back to testing the changes based on #34 later on.

**Comment by wtfzdotnet** [comment]
Thanks for reporting the issue, I'll get back to this ticket again later on with #34

**Comment by TheOne404** [comment]
any update on this issue ?
