### ISSUE TITLE
Symfony 6

### ISSUE THREAD

**Issue by r3sist** [php-tmdb/symfony#40]
Dear Developers,

Is it possible to make this library compatible with Symfony 6, which is the actual stable version of Symfony? It would be very useful for me.

This and *php-tmdb/api* packages require some Symfony libs with version 4 or 5 but less than 6 (e.g. `"symfony/event-dispatcher": "^5.0,<6"`). Since 5.4 is well supported in this package, and there is no difference between Symfony 5.4 and 6.0 in general, I think it could be possible without any problem. Or do you know any Symfony 5.* feature usage in your libs that was deprecated already in 5.4? 

Thank you!

**Comment by m-vdv** [comment]
+1 Would love to see official support for Symfony 6.

Ps: readme usage info would need an update as well, since Symfony 5.4 and up now use method or constructor injection in the controller.
