### ISSUE TITLE
There is no extension able to load the configuration for "tmdb"

### ISSUE THREAD

**Issue by Guilain** [php-tmdb/symfony#5]
Hello, thanks for this helpfull bundle, but, i can't init it and there is a git error :(

-> There is no extension able to load the configuration for "tmdb"
-> symfony/Resources/config/repositories.xml -> line 16 to 20

**Comment by wtfzdotnet** [comment]
I have done some untested refactorings, I'll be working on a release in a bit :). Been moving all of the repositories to this new organization just today so things are a bit messy right now!

**Comment by wtfzdotnet** [comment]
Did some updates on the `2.0` branch, should work with instructions provided, do note I might be blowing things up again tomorrow as I'm not entirely done yet with all te work for an official version release.

**Comment by Guilain** [comment]
ok ok, I will do some tests ;)

**Comment by wtfzdotnet** [comment]
I'll be hitting the bed now, if you come across something just leave me some comments or pull requests and I'll look at them tomorrow.
